"""
Codebook + thematic coding for the Nonogram open-text responses.

The codebook below was built bottom-up (grounded) by reading every free-text
response in backend/logs. Two schemes are used:

  * DIFFICULTY THEMES  -> applied to "rating_reason" and "comments" responses
      (the "why did you rate it / what made it hard or easy" questions).
  * STRATEGY TAXONOMY  -> applied to the "strategy" responses.

CODING maps a response_id (from derived/text_responses.csv, generated by
01_export_text_responses.py) to the list of codes assigned to it. Responses
that are blank/"n/a"/uninformative are intentionally absent (treated as
"no codeable content"). Each response may carry multiple codes (multi-label).

This file is hand-authored data; it is the reproducible record of the LLM-
assisted thematic coding pass and contains no live computation.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Codebooks
# --------------------------------------------------------------------------- #
DIFFICULTY_THEMES: dict[str, dict[str, str]] = {
    "FOOT": {
        "name": "Starting footholds / forced lines",
        "definition": (
            "References to the availability (easier) or absence (harder) of "
            "lines that can be solved immediately: 'freebies', 'fixed/"
            "guaranteed arrangements', full rows, lines that sum to the grid "
            "width, or 'where to start'."
        ),
    },
    "CLUE": {
        "name": "Clue magnitude",
        "definition": (
            "Difficulty attributed to the size/composition of the clue numbers "
            "(large numbers easier; many small numbers / lots of 1s harder)."
        ),
    },
    "PROP": {
        "name": "Constraint propagation / chaining",
        "definition": (
            "Deductions chain smoothly: one solved line/cell forces the next, "
            "working off crossing rows/columns; emphasis on logical flow."
        ),
    },
    "AMBIG": {
        "name": "Combinatorial ambiguity / overlap reasoning",
        "definition": (
            "Having to weigh many possible arrangements, consider overlaps of "
            "extremes, or cope with uncertainty about where blocks go."
        ),
    },
    "GUESS": {
        "name": "Guessing / certainty",
        "definition": (
            "Salient mention of guessing, trial-and-error, or (lack of) a "
            "deterministic/logical path forward."
        ),
    },
    "HINT": {
        "name": "Hint usage",
        "definition": "References to using, waiting for, or relying on the Hint button.",
    },
    "ERR": {
        "name": "Mistakes / error recovery",
        "definition": (
            "Made a mistake, hard to trace back, had to restart, undo, or "
            "recover from a wrong deduction."
        ),
    },
    "LEARN": {
        "name": "Learning / practice / fatigue",
        "definition": (
            "Order/experience effects within the session: first time, warming "
            "up, getting better with practice, learning techniques, or fatigue."
        ),
    },
    "LOAD": {
        "name": "Cognitive load / tracking",
        "definition": (
            "Mental bookkeeping burden: keeping track of state, remembering "
            "possibilities, holding deductions in the head, feeling overwhelmed."
        ),
    },
    "VIS": {
        "name": "Visual / spatial layout",
        "definition": (
            "Spatial layout cues: edges vs middle starts, sparsity/blank space, "
            "1s blending together, grid size, lack of a picture/symmetry."
        ),
    },
    "TIME": {
        "name": "Time pressure",
        "definition": "Difficulty/behaviour driven by time limits or social time pressure.",
    },
    "UI": {
        "name": "Interface friction",
        "definition": (
            "Comments about the tool/UI: cross-toggle swapping colours, button "
            "placement, hint refresh timing, wanting paper annotations."
        ),
    },
    "AFF": {
        "name": "Confidence / affect",
        "definition": (
            "Affective / self-efficacy framing: confidence, frustration, "
            "nervousness, enjoyment, gut-feeling difficulty judgements."
        ),
    },
}

STRATEGY_TAXONOMY: dict[str, dict[str, str]] = {
    "S_FORCED": {
        "name": "Forced-line solving",
        "definition": (
            "Find and fill fully-determined lines first (lines summing to grid "
            "width, '(N-1)+T=10', guaranteed/fixed lines, certain cells)."
        ),
    },
    "S_CONSTR": {
        "name": "Most-constrained-first ordering",
        "definition": (
            "Heuristic of starting from the most constrained lines: largest "
            "sum, largest numbers, or the most numbers in a line."
        ),
    },
    "S_OVERLAP": {
        "name": "Overlap analysis",
        "definition": (
            "Compare extreme (leftmost/rightmost) placements and fill the cells "
            "common to all arrangements; 'guaranteed in every combination'."
        ),
    },
    "S_EDGE": {
        "name": "Edge / anchor exploitation",
        "definition": (
            "Use borders and the start/end of sequences, or extend from cells "
            "already filled at an edge."
        ),
    },
    "S_CROSS": {
        "name": "Row/column cross-referencing",
        "definition": (
            "After each fill, propagate to the perpendicular rows/columns; "
            "iterate row<->column until stuck."
        ),
    },
    "S_NEG": {
        "name": "Negative marking (X-ing whites)",
        "definition": (
            "Actively cross out / X cells that must be empty to constrain the "
            "remaining space and track the board."
        ),
    },
    "S_TRIAL": {
        "name": "Trial-and-error / contradiction",
        "definition": (
            "Make guesses, enumerate possibilities, or assume-and-check for "
            "contradictions, then backtrack."
        ),
    },
    "S_HINT": {
        "name": "Hint-as-tool",
        "definition": (
            "Deliberate use of the Hint button to verify guesses, debug "
            "mistakes, or unstick progress."
        ),
    },
}

# --------------------------------------------------------------------------- #
# Coding (response_id -> codes)
# --------------------------------------------------------------------------- #
CODING: dict[str, list[str]] = {
    # ---- rating_reason ----
    "R0000": ["FOOT", "CLUE"],
    "R0001": ["FOOT", "VIS"],
    "R0002": ["FOOT", "AMBIG"],
    "R0003": ["HINT", "ERR"],
    "R0004": ["HINT", "AMBIG"],
    "R0005": ["HINT", "AMBIG"],
    "R0006": ["LEARN"],
    "R0007": ["LEARN"],
    "R0008": ["ERR", "LEARN"],
    "R0009": ["HINT"],
    "R0010": ["PROP"],
    "R0012": ["CLUE", "PROP", "GUESS"],
    "R0013": ["CLUE", "FOOT"],
    "R0014": ["FOOT", "AMBIG"],
    "R0015": ["LEARN"],
    "R0016": ["FOOT", "VIS"],
    "R0017": ["AFF"],
    "R0019": ["ERR", "GUESS"],
    "R0020": ["LEARN"],
    "R0021": ["GUESS"],
    "R0022": ["GUESS"],
    "R0023": ["GUESS", "FOOT"],
    "R0024": ["LEARN"],
    "R0025": ["LEARN"],
    "R0026": ["LEARN"],
    "R0027": ["FOOT", "VIS", "CLUE"],
    "R0028": ["FOOT", "VIS", "CLUE"],
    "R0029": ["CLUE", "FOOT", "VIS", "PROP"],
    "R0030": ["GUESS", "HINT", "FOOT"],
    "R0031": ["GUESS", "HINT"],
    "R0032": ["GUESS", "HINT"],
    "R0033": ["ERR"],
    "R0034": ["ERR", "CLUE", "AMBIG"],
    "R0035": ["LEARN", "ERR"],
    "R0036": ["AFF"],
    "R0037": ["AFF"],
    "R0038": ["AFF"],
    "R0039": ["FOOT", "CLUE"],
    "R0040": ["FOOT", "CLUE"],
    "R0041": ["FOOT", "CLUE"],
    "R0045": ["FOOT", "VIS", "CLUE"],
    "R0046": ["FOOT", "AMBIG", "PROP"],
    "R0047": ["FOOT", "CLUE", "LOAD", "PROP", "VIS"],
    "R0048": ["LEARN"],
    "R0049": ["GUESS"],
    "R0050": ["FOOT", "CLUE"],
    "R0051": ["HINT", "GUESS"],
    "R0052": ["GUESS", "HINT"],
    "R0053": ["FOOT", "CLUE", "GUESS", "PROP"],
    "R0054": ["CLUE", "FOOT"],
    "R0055": ["FOOT", "PROP", "AMBIG", "CLUE"],
    "R0056": ["FOOT", "VIS"],
    "R0057": ["GUESS", "LOAD"],
    "R0058": ["CLUE", "PROP"],
    "R0059": ["LEARN", "GUESS"],
    "R0063": ["CLUE", "FOOT"],
    "R0064": ["FOOT"],
    "R0065": ["FOOT"],
    "R0066": ["HINT"],
    "R0067": ["HINT"],
    "R0069": ["CLUE", "FOOT", "LEARN"],
    "R0070": ["CLUE", "FOOT", "LEARN"],
    "R0071": ["CLUE", "VIS", "FOOT"],
    "R0072": ["CLUE", "FOOT"],
    "R0073": ["CLUE", "FOOT", "PROP"],
    "R0074": ["CLUE", "FOOT", "PROP"],
    "R0075": ["FOOT", "GUESS", "HINT"],
    "R0078": ["GUESS", "AMBIG"],
    "R0079": ["LEARN"],
    "R0080": ["LEARN", "AMBIG"],
    "R0081": ["LEARN"],
    "R0084": ["LEARN"],
    "R0085": ["PROP"],
    "R0086": ["ERR"],
    "R0087": ["LEARN"],
    "R0088": ["GUESS"],
    "R0089": ["CLUE", "FOOT"],
    "R0090": ["LEARN"],
    "R0093": ["FOOT", "PROP"],
    "R0094": ["AMBIG"],
    "R0095": ["HINT", "ERR"],
    "R0096": ["LEARN", "AFF"],
    "R0097": ["LEARN", "FOOT"],
    "R0098": ["LEARN", "FOOT", "VIS"],
    "R0099": ["AFF"],
    "R0100": ["AFF"],
    "R0101": ["HINT"],
    "R0102": ["CLUE", "FOOT"],
    "R0103": ["CLUE"],
    "R0104": ["CLUE"],
    "R0105": ["HINT"],
    "R0106": ["HINT"],
    "R0107": ["HINT"],
    "R0108": ["FOOT", "CLUE"],
    "R0109": ["FOOT", "LEARN"],
    "R0110": ["FOOT", "LEARN"],
    "R0111": ["FOOT", "AMBIG", "PROP"],
    "R0112": ["FOOT", "AMBIG", "CLUE"],
    "R0113": ["FOOT", "VIS", "PROP"],
    "R0114": ["PROP"],
    "R0115": ["ERR", "AMBIG", "HINT"],
    "R0116": ["PROP", "LEARN"],
    "R0117": ["LEARN"],
    "R0120": ["CLUE", "FOOT"],
    "R0121": ["CLUE", "FOOT"],
    "R0122": ["VIS", "FOOT", "PROP"],
    "R0126": ["FOOT", "PROP"],
    "R0127": ["GUESS"],
    "R0128": ["GUESS"],
    "R0129": ["HINT"],
    "R0130": ["HINT"],
    "R0131": ["HINT"],
    "R0132": ["GUESS", "FOOT"],
    "R0133": ["FOOT"],
    "R0134": ["GUESS", "AMBIG"],
    "R0135": ["FOOT", "PROP"],
    "R0136": ["FOOT", "PROP"],
    "R0137": ["FOOT", "VIS"],
    "R0138": ["VIS", "FOOT"],
    "R0139": ["ERR"],
    "R0140": ["LEARN"],
    "R0141": ["FOOT", "PROP"],
    "R0143": ["FOOT", "GUESS"],
    "R0144": ["FOOT"],
    "R0145": ["FOOT", "LEARN"],
    "R0146": ["FOOT"],
    "R0147": ["CLUE"],
    "R0148": ["LEARN"],
    "R0150": ["FOOT"],
    "R0151": ["FOOT"],
    "R0152": ["FOOT"],
    "R0153": ["CLUE"],
    "R0154": ["CLUE"],
    "R0156": ["FOOT"],
    "R0157": ["FOOT", "PROP"],
    "R0159": ["GUESS", "LEARN"],
    "R0160": ["FOOT", "GUESS", "TIME"],
    "R0162": ["LEARN"],
    "R0165": ["LEARN"],
    "R0166": ["LEARN"],
    "R0167": ["FOOT", "CLUE"],
    "R0168": ["FOOT"],
    "R0169": ["FOOT"],
    "R0170": ["FOOT", "LOAD"],
    "R0171": ["FOOT", "AMBIG", "LOAD"],
    "R0172": ["GUESS", "FOOT"],
    "R0173": ["ERR", "HINT", "GUESS"],
    "R0174": ["PROP"],
    "R0176": ["AMBIG", "PROP"],
    "R0177": ["HINT"],
    "R0179": ["LEARN"],
    "R0180": ["LEARN", "AMBIG", "FOOT"],
    "R0184": ["FOOT"],
    "R0185": ["FOOT", "AMBIG", "CLUE"],
    "R0186": ["LEARN", "FOOT"],
    "R0189": ["LEARN", "ERR", "FOOT"],
    "R0190": ["LEARN", "FOOT"],
    "R0192": ["CLUE", "FOOT"],
    "R0193": ["AMBIG", "FOOT"],
    "R0194": ["LEARN", "PROP"],
    "R0195": ["FOOT", "AMBIG", "LOAD"],
    "R0196": ["FOOT", "AMBIG", "LOAD"],
    "R0197": ["FOOT", "AMBIG", "LOAD"],
    "R0198": ["LEARN"],
    "R0199": ["HINT"],
    "R0201": ["LEARN", "FOOT"],
    "R0202": ["LEARN", "FOOT"],
    # ---- comments ----
    "R0205": ["VIS", "GUESS"],
    "R0208": ["HINT"],
    "R0211": ["HINT", "UI"],
    "R0214": ["CLUE"],
    "R0217": ["UI", "ERR"],
    "R0220": ["CLUE"],
    "R0223": ["CLUE", "FOOT"],
    "R0229": ["CLUE", "AMBIG"],
    "R0232": ["VIS"],
    "R0235": ["LEARN", "FOOT", "GUESS", "HINT"],
    "R0238": ["CLUE"],
    "R0241": ["LEARN"],
    "R0244": ["AMBIG"],
    "R0250": ["VIS"],
    "R0253": ["HINT", "UI"],
    "R0256": ["HINT", "GUESS"],
    "R0259": ["VIS"],
    "R0262": ["LEARN", "HINT", "AFF"],
    "R0268": ["FOOT"],
    "R0277": ["CLUE", "VIS"],
    "R0280": ["GUESS", "FOOT"],
    "R0283": ["LEARN"],
    "R0286": ["LEARN"],
    "R0289": ["LOAD", "UI"],
    "R0295": ["LEARN"],
    "R0298": ["LOAD"],
    "R0301": ["FOOT", "AMBIG", "LEARN"],
    "R0304": ["CLUE"],
    "R0310": ["CLUE"],
    "R0313": ["LEARN"],
    "R0316": ["AMBIG", "FOOT"],
    "R0319": ["FOOT", "AMBIG"],
    "R0325": ["CLUE", "VIS"],
    "R0334": ["CLUE"],
    "R0340": ["FOOT", "AMBIG", "VIS"],
    "R0343": ["TIME", "AFF"],
    "R0346": ["FOOT"],
    "R0352": ["VIS"],
    "R0355": ["GUESS", "AFF"],
    "R0358": ["HINT"],
    "R0361": ["CLUE", "FOOT"],
    "R0364": ["TIME", "LEARN"],
    "R0367": ["LEARN"],
    "R0370": ["UI", "LOAD"],
    "R0373": ["FOOT"],
    "R0376": ["PROP", "AMBIG", "GUESS"],
    "R0379": ["LEARN", "AFF"],
    "R0382": ["UI"],
    "R0385": ["FOOT"],
    "R0388": ["AFF"],
    "R0397": ["HINT"],
    "R0400": ["FOOT", "CLUE"],
    "R0403": ["AFF"],
    "R0406": ["LEARN"],
    # ---- strategy ----
    "R0204": ["S_FORCED", "S_CONSTR", "S_OVERLAP", "S_NEG"],
    "R0207": ["S_HINT"],
    "R0210": ["S_FORCED", "S_EDGE", "S_OVERLAP", "S_NEG", "S_HINT"],
    "R0213": ["S_FORCED"],
    "R0216": ["S_FORCED", "S_EDGE", "S_OVERLAP"],
    "R0219": ["S_FORCED"],
    "R0222": ["S_FORCED", "S_CROSS"],
    "R0225": ["S_FORCED", "S_TRIAL"],
    "R0228": ["S_FORCED", "S_NEG", "S_HINT"],
    "R0231": ["S_FORCED", "S_NEG", "S_OVERLAP"],
    "R0234": ["S_FORCED", "S_NEG", "S_OVERLAP", "S_TRIAL", "S_HINT"],
    "R0237": ["S_CONSTR", "S_CROSS", "S_NEG"],
    "R0240": ["S_FORCED", "S_OVERLAP", "S_CROSS"],
    "R0243": ["S_CONSTR", "S_OVERLAP"],
    "R0249": ["S_FORCED", "S_EDGE", "S_OVERLAP", "S_NEG", "S_CROSS"],
    "R0252": ["S_CONSTR", "S_FORCED", "S_HINT"],
    "R0255": ["S_CONSTR", "S_TRIAL"],
    "R0258": ["S_CONSTR", "S_OVERLAP", "S_EDGE"],
    "R0261": ["S_CONSTR", "S_OVERLAP"],
    "R0267": ["S_CONSTR", "S_FORCED", "S_NEG", "S_CROSS"],
    "R0273": ["S_TRIAL", "S_HINT"],
    "R0276": ["S_FORCED", "S_CROSS"],
    "R0279": ["S_FORCED", "S_CROSS"],
    "R0282": ["S_FORCED"],
    "R0285": ["S_HINT"],
    "R0288": ["S_FORCED", "S_OVERLAP", "S_CROSS"],
    "R0291": ["S_FORCED"],
    "R0294": ["S_CROSS"],
    "R0297": ["S_FORCED", "S_EDGE", "S_OVERLAP"],
    "R0300": ["S_FORCED", "S_NEG"],
    "R0303": ["S_CONSTR"],
    "R0306": ["S_FORCED"],
    "R0309": ["S_OVERLAP"],
    "R0312": ["S_FORCED", "S_OVERLAP", "S_CROSS"],
    "R0315": ["S_FORCED", "S_EDGE", "S_OVERLAP", "S_NEG"],
    "R0318": ["S_OVERLAP", "S_TRIAL"],
    "R0321": ["S_TRIAL", "S_HINT", "S_NEG"],
    "R0324": ["S_CONSTR", "S_OVERLAP", "S_EDGE"],
    "R0327": ["S_CROSS"],
    "R0330": ["S_TRIAL"],
    "R0333": ["S_FORCED", "S_NEG"],
    "R0336": ["S_FORCED", "S_TRIAL", "S_NEG"],
    "R0339": ["S_NEG", "S_CONSTR", "S_CROSS"],
    "R0342": ["S_OVERLAP", "S_CROSS"],
    "R0345": ["S_FORCED", "S_TRIAL"],
    "R0348": ["S_CROSS", "S_NEG"],
    "R0351": ["S_FORCED"],
    "R0354": ["S_FORCED", "S_TRIAL", "S_CROSS"],
    "R0357": ["S_CONSTR"],
    "R0360": ["S_FORCED", "S_OVERLAP", "S_NEG"],
    "R0363": ["S_FORCED", "S_TRIAL"],
    "R0366": ["S_FORCED", "S_HINT", "S_CROSS"],
    "R0369": ["S_TRIAL"],
    "R0372": ["S_FORCED", "S_OVERLAP"],
    "R0375": ["S_FORCED", "S_OVERLAP", "S_NEG"],
    "R0378": ["S_OVERLAP", "S_EDGE", "S_CROSS"],
    "R0381": ["S_FORCED", "S_HINT"],
    "R0384": ["S_OVERLAP", "S_CONSTR"],
    "R0387": ["S_FORCED", "S_NEG", "S_EDGE", "S_OVERLAP"],
    "R0390": ["S_FORCED", "S_OVERLAP", "S_NEG", "S_HINT"],
    "R0393": ["S_FORCED", "S_OVERLAP", "S_CROSS"],
    "R0396": ["S_FORCED", "S_OVERLAP", "S_NEG"],
    "R0399": ["S_FORCED", "S_OVERLAP", "S_EDGE"],
    "R0402": ["S_OVERLAP", "S_FORCED", "S_EDGE", "S_NEG"],
    "R0405": ["S_NEG", "S_FORCED", "S_OVERLAP"],
}

ALL_DIFFICULTY_CODES = list(DIFFICULTY_THEMES.keys())
ALL_STRATEGY_CODES = list(STRATEGY_TAXONOMY.keys())
